[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Telegram bot with Wasabi storage and FastAPI web interface"
requires-python = ">=3.11"

dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "boto3>=1.40.25",
    "pyrogram>=2.0.106",
    "python-dotenv>=1.1.1",
    "tgcrypto>=1.2.5",
    "asyncio-throttle>=1.0.2",
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
    "aiobotocore>=2.24.2",
    "humanize>=4.13.0",
]
